# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project2
pod 'Alamofire' , '~> 4.7'
  target 'Project2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project2UITests' do
    # Pods for testing
  end

end
